### ISSUE TITLE
QRコードを読み込む

### ISSUE THREAD

**Issue by cardseditor** [Dev-roll/thundercard#27]
## 完了要件
- [x] QRコードを認識してカメラを終了
- [x] ユーザーデータを取得

**Comment by keigomichi** [comment]
参考にしたWebサイト
- https://pub.dev/packages/qr_code_scanner
- https://zenn.dev/seya/articles/6e15432cfe327d
- https://zuma-lab.com/posts/flutter-qr-code-scanner-camera
