### ISSUE TITLE
NotificationsページにてAppbarの戻るボタンが表示される場合がある

### ISSUE THREAD

**Issue by keigomichi** [Dev-roll/thundercard#91]
## 再現方法
Thundercardページにて「名刺交換」→ コード読み取り → ... → Notificationsページへ移動

**Comment by notchcoder** [comment]
## 考察

- 「戻るボタン」が表示される
- Androidの「戻る」操作でページ遷移する
  - AppBarは、ページのスタックが残っている際に自動で戻るボタンを表示する
  - いずれも、戻ることにより`scan_qr_code.dart`ページに遷移する
  - 以上の事象から、コード読み取りに成功した場合、`scan_qr_code.dart`ページのスタックが残ってしまっている


## 解決方法案

- [ ] `Navigator.of(context).push();`を`Navigator.of(context).pop();`に変更する

**Comment by notchcoder** [comment]
## 完了要件

- [ ] AppBarに戻るボタンを表示させないようにする
